#File: docker-compose.yml
#Description: This file defines the Docker Compose configuration for setting up the application and database containers.
#Author: Alexander D Spies
#Date: 9 March 2024
 
#This YAML file specifies the services, environment variables, ports, and volumes for the application and database containers.
#It uses PostgreSQL as the database and sets up environment variables for connecting the Spring Boot application to the database.
 
#Usage:
  #- Customize the environment variables, image versions, and other settings as needed.
  #- Run `docker-compose up` to build and start the containers.
  
  #For more information about Docker Compose, refer to the official documentation:
  #- Docker Compose: https://docs.docker.com/compose/
 

version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: tvecom
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/tvecom
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123456
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - db
    ports:
      - "8080:8080"

volumes:
  pgdata:
